[main]
font=monospace:size=14
dpi-aware=auto
icon-theme=Papirus
width=45
lines=12
horizontal-pad=15
vertical-pad=15
inner-pad=10

# Launch commands and terminal
terminal=foot -e
prompt="❯ "
layer=overlay

[colors]
background=081a23ea
text=f8f8f2ff
match=9beafdff
selection=64677fff
selection-text=f8f8f2ff
selection-match=9beafdff
border=50d0a0ff
input=f8f8f2ff

[border]
radius=12
width=3

[dmenu]
exit-immediately-if-empty=yes

